[plugin]
repository = "https://github.com/behdjtsetlas/felix.git"
commit = "1ecd832932ad455b31f04cb1bdd4ece5ca20eb02"
owners = [ "behdjtsetlas" ]
project_path = "Felix"
changelog = "Initial submission for testing track."
